import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "../components/ui/sonner";
import Providers from "@/Providers";
import { signOut, useSession } from "next-auth/react";
import { UserProvider } from "../context/UserContext";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { WishlistProvider } from "@/context/WishlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <WishlistProvider>
            <Navbar />
            <Toaster />
            {children}
          </WishlistProvider>
        </UserProvider>
      </body>
    </html>
  );
}
